enable-magisk-update = true # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 1

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config
[YTMusic]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
version = "8.34.51"
arch = "both"
build-mode = "module"
excluded-patches = "'GmsCore support' 'Spoof client'"

[TikTokASIA]
apkmirror-dlurl = "https://apkmirror.com/apk/tiktok-pte-ltd/tik-tok/"
arch = "both"
included-patches = "'SIM spoof'"
version = "7.43.0.800596475"
[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
arch = "both"
build-mode = "module"

[GooglePhotos]
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/photos/"

arch = "both"
build-mode = "module"
included-patches = "'Spoof features'"
exclusive-patches = true
