enable-magisk-update = true # set this to false if you do not want to receive updates for the module in magisk app
parallel-jobs = 1

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[Music]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube-music/"
arch = "arm64-v8a"
build-mode = "module"
version = "auto"
included-patches = "'Permanent repeat' 'Hide category bar'"
excluded-patches = "'GmsCore support' 'Spoof client'"

[Tiktok]
apkmirror-dlurl = "https://apkmirror.com/apk/tiktok-pte-ltd/tik-tok-including-musical-ly/"
arch = "arm64-v8a"
version = "auto"
included-patches = "'SIM spoof'"

[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
arch = "arm64-v8a"
build-mode = "module"
version = "auto"
included-patches = "'Remove player controls background'"
excluded-patches = "'GmsCore support'"

[GooglePhotos]
build-mode = "module"
arch = "arm64-v8a"
version = "auto"
uptodown-dlurl = "https://google-photos.en.uptodown.com/android"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/photos/"
included-patches = "'Spoof features'"
exclusive-patches = true
