name: Scheduled CI Maintenance

on:
  workflow_dispatch:
  schedule:
    - cron: "0 19 * * *"  # 19:00 UTC (00:00 ЕКБ)

jobs:
  cleanup:
    name: Cleanup Old Runs
    permissions:
      actions: write  # Минимальные необходимые права
      contents: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Delete Old Workflow Runs
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Удаляем все запуски кроме последних 5 (экономия ресурсов)
          gh run list --limit 400 --json databaseId -q '.[].databaseId' \
          | tail -n+6 \
          | xargs -r -IID gh api "repos/$GITHUB_REPOSITORY/actions/runs/ID" -X DELETE

  build:
    name: Daily Build
    needs: cleanup
    permissions:
      contents: read
    uses: ./.github/workflows/build.yml
    secrets: inherit
