name: Scheduled CI Maintenance

on:
  workflow_dispatch:
  schedule:
    - cron: "0 19 * * *"

jobs:
  cleanup:
    name: Cleanup Old Runs
    permissions:
      actions: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Delete Old Runs
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh run list --limit 400 --json databaseId -q '.[].databaseId' \
          | tail -n+6 \
          | xargs -r -IID gh api "repos/$GITHUB_REPOSITORY/actions/runs/ID" -X DELETE

  build:
    name: Daily Build
    needs: cleanup
    permissions:  # Явно объявляем необходимые права
      actions: write
      contents: write
      checks: write
      packages: write
      pull-requests: write
    uses: ./.github/workflows/build.yml
    secrets: inherit
